### PR TITLE
Don't use root user for qBittorrent

### PR DESCRIPTION
**Pull request by leon-marzahn**
I'm actually using your image and it's amazing! Here are some improvements to make it work with the *-arr stack hardlinks :)

Additions:
- Ability to set PUID, PGID, UMASK and TZ
- qBittorrent is not run as root user anymore making download file permissions not root (Which allows for hardlinking from the *-arr stack)
- README update

### CODE REVIEW

**Comment by leon-marzahn** [comment]
Also, i did some more leak testing on my end and it seems to be working well. The only thing i'm thinking about is if it's better to change the network interface in qBittorrent to the tunnel by default?

**Comment by j4ym0** [comment]
@leon-marzahn If I remember correctly I had trouble with early versions of qbittorrent. I will look into setting the tunnel as the default interface in qbittorrent.

**Comment by j4ym0** [comment]
@leon-marzahn Thank you for your edits, I will review and test on all platforms.

Question: Is the timezone relevant as it would only affect the data within the container and downloaded data is stored in a mounted volume?

**Comment by leon-marzahn** [comment]
> @leon-marzahn Thank you for your edits, I will review and test on all platforms.
> 
> Question: Is the timezone relevant as it would only affect the data within the container and downloaded data is stored in a mounted volume?

It's not the most important, but the linuxserver team always adds it. I reckon it's relevant when your server is hosted somewhere and you want to make sure any dates are the same in your docker container.

**Comment by leon-marzahn** [comment]
> @leon-marzahn If I remember correctly I had trouble with early versions of qbittorrent. I will look into setting the tunnel as the default interface in qbittorrent.

I think i tried it, and it reverted back to eth0 anyways. But i also don't know how openvpn works, i was just curious if there is a network interface that doesn't use the vpn, but i'm unsure if that's actually how it works 😅

**Comment by j4ym0** [comment]
@leon-marzahn Fair enough. It's not a big change

**Comment by leon-marzahn** [comment]
> @leon-marzahn That does seem familiar. The firewall rules are designed to block all traffic to the outside without going through the VPN tunnel. With exception to the IP addresses of the chosen VPN region.

Okay cool. that should be fine then. In that case it shouldn't matter which network interface you use

**Pull request merged**
